### ISSUE TITLE
every lua files have 1Ko

### ISSUE THREAD

**Issue by Ukushino** [EinsatzGruppen/EinsatzScan#4]
Hey,
I figured out that when I have finished to download all lua files, every .lua have 1Ko and when you open one of them
`return gluapack()()`

Do we have something to "bypass" that ?

**Comment by SchwarzKruppzo** [comment]
It should be unpacked in "<IP>/engine_calls/" folder somewhere anyway. Try check it.

You can also provide server IP so I'll try investigate this issue.

**Comment by MIKADE1337** [comment]
Hello , i got the problem to, can you test ist to for me, here the ip : 54.38.154.169:27015

**Comment by MIKADE1337** [comment]
@SchwarzKruppzo Can you please help?, is very important
[54.38.154.169_27015_1711847700.zip](https://github.com/EinsatzGruppen/EinsatzScan/files/14817801/54.38.154.169_27015_1711847700.zip)

**Comment by NercoLive** [comment]
This is due to the server using the GluaPack addon which improves the way files are packed and sent to the client, which also break standard lua file dumpers from working : https://www.gmodstore.com/market/view/gluapack

As mentionned on the addon's page, "gluapack will pretty much render any typical "clientside Lua file dumper" that a player may join with mostly useless, unless the dumper is specially crafted to also unpack gluapack's virtual file system.".

**Comment by SchwarzKruppzo** [comment]
> This is due to the server using the GluaPack addon which improves the way files are packed and sent to the client, which also break standard lua file dumpers from working : https://www.gmodstore.com/market/view/gluapack
> 
> As mentionned on the addon's page, "gluapack will pretty much render any typical "clientside Lua file dumper" that a player may join with mostly useless, unless the dumper is specially crafted to also unpack gluapack's virtual file system.".

Latest release is able to work with gluapacks.
